### ISSUE TITLE
Flash on nav click

### ISSUE THREAD

**Issue by ivanstegic** [ten7/tractorbeam.ten7.com#4]
When you click on "Support" in the nav, the dropdown menu appears very quickly as a flash. Please fix, see video: https://www.loom.com/share/04697b62b0db41679f6bebe564a34b6e

**Comment by above9Sq** [comment]
https://github.com/ten7/tractorbeam.ten7.com/pull/5

**Comment by ivanstegic** [comment]
Thanks for the fix
